### PR TITLE
doc(README) : better doc, typo & MEAP book

### PR DESCRIPTION
**Pull request by adriens**
# :grey_question: About

This PRs:

- :heavy_check_mark: Fixes a typo
- :heavy_check_mark: Adds the link to [DuckDB in Action (MEAP) book](https://www.manning.com/books/duckdb-in-action)

# :point_up: DoD

Be sure these datas will be available on the marketplace preview of the action

### CODE REVIEW

**Comment by michael-simons** [comment]
Aaaaw <3 Marvelous.

**Comment by adriens** [comment]
> Aaaaw <3 Marvelous.

I thought that getting all the things at a same place would provide an optimal DevEx :thought_balloon:

**Comment by adriens** [comment]
@mbarre , when will it be available on the marketplace ?
image

**Comment by mbarre** [comment]
Done.

**Comment by adriens** [comment]
:raised_hands: 

@michael-simons :point_down: 
image

**Pull request merged**
